### ISSUE TITLE
Milestone ability cards

### ISSUE THREAD

**Issue by Nimeroni** [cmlenius/gloomhaven-card-browser#11]
Hi !

Do you plan to add the Milestone ability cards ? They are one card per class added to your card pool when you finish your milestone objective. They are added by the Trail of Ashes expansions, and concern both Trail of Ashes and Crimson scales class.

Maybe put a spoiler toggle in case people don't want to get spoiled their M cards (near the level slider or something).

You can find them here : https://github.com/any2cards/worldhaven/tree/master/images/milestone-ability-cards/trail-of-ashes

**Comment by cmlenius** [comment]
Hi,

I'll be sure to add them. I've never actually played Crimson Scales before
so i'm not too familiar with all the content. Thanks for letting me know.

**Comment by Nimeroni** [comment]
You missed the M card for the Luminary.
