### ISSUE TITLE
Some inaccuracies / bugs on the FH side

### ISSUE THREAD

**Issue by Suikanen** [cmlenius/gloomhaven-card-browser#26]
Item #49 Cruel Dagger had a card misprint in 1st edition; official FAQ says it should be a Spent item.
From https://boardgamegeek.com/thread/3001013/official-faq-frosthaven-no-rules-questions-please:
"Item 049 This item is missing a Spent symbol. "
Item #148 Circlet of Sanctity is a Flippable item, but is missing the flip-around button from the webpage UI.

PS. Excellent depository of information, thank you for creating it!

**Comment by cmlenius** [comment]
Thanks for pointing it out, should be fixed now.
