### ISSUE TITLE
Trail of Ashes character class names spoiled

### ISSUE THREAD

**Issue by ding493** [cmlenius/gloomhaven-card-browser#27]
In the Settings tab (atop right), for all other games, the icon name is displayed.  For Trail of Ashes, the class names are displayed, spoiling the names.  I assume this is unintentional and thus a bug.

Also consider the Trail of Ashes V class hidden to URL-only, since it is technically a hidden class.

By the way, this site is perfection and you are a genius for building it.

-Steve.

**Comment by cmlenius** [comment]
👍

**Comment by ding493** [comment]
Confirmed. 

Thank you.
