### ISSUE TITLE
Starting Cards Selection/Deckbuilder

### ISSUE THREAD

**Issue by alexzhaohong** [cmlenius/gloomhaven-card-browser#30]
Do you think you will add a feature that will allow choosing a starting hand? Similar to https://asgrabowski.github.io or https://www.gloomhaven-deck.com.

As an additional feature, have you considered an export feature? For other card games, an export feature is also implemented for deck lists. I think an export feature for a plaint text list of card names would be a nice feature to have for Gloomhaven, as to better share starting hand strategies for certain scenarios.

**Comment by cmlenius** [comment]
Unfortunately I probably won't be adding that feature. It was always meant to be a very streamlined app for browsing cards and I don't think the feature would be used enough to warrant the added complexity. Most other card games are far more complex in terms of deck building than Gloomhaven so a lot more people are looking to build/store decks online in addition to browsing cards.

Sorry :/

**Comment by alexzhaohong** [comment]
No worries, I knew this would be a stretch in scope for your app, but I wanted to know your perspective.

How do you feel about perks and character mats? Now that Gloomhaven 2e characters will have non-AMD (Attack modifier deck) perks, it helps to see those.

**Comment by cmlenius** [comment]
I usually just put up content when its available on https://github.com/any2cards/worldhaven since that's where i get all the images from

**Comment by alexzhaohong** [comment]
Ah, I meant like, non-AMD perks such as Bannerspear's unique perks. 
https://github.com/any2cards/worldhaven/blob/master/images/attack-modifiers/frosthaven/BN/fh-pe-bn-01.png

![](https://github.com/any2cards/worldhaven/blob/master/images/attack-modifiers/frosthaven/GE/fh-pe-ge-01.png)
