### ISSUE TITLE
Bladeswarm

### ISSUE THREAD

**Issue by christopherboote** [cmlenius/gloomhaven-card-browser#32]
Now that Envelope X is public knowledge, is it time to put the Bladeswarm cards in?

**Comment by cmlenius** [comment]
Is it public knowledge now? The cards are already in the app anyway they were just "hidden" (you had to manually change the URL.

https://www.gloomhavencards.com/gh/characters/BS,

**Comment by christopherboote** [comment]
Yeah, it's been 'leaked' as of this week as part of the launch of GH 2.0

Including all the cards to L5

I guessed you had already sorted it behind the scenes :)

BTW do you have some sort of tip jar? I use the app literally every day 
when answering GH/JotL/CS/FSH queries

Chris

On 07/07/2023 22:16, Cameron Lenius wrote:

> Is it public knowledge now? The cards are already in the app anyway 
> they were just "hidden" (you had to manually change the URL.
> 
> https://www.gloomhavencards.com/gh/characters/BS,
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/cmlenius/gloomhaven-card-browser/issues/32#issuecomment-1626134559
[2]

**Comment by cmlenius** [comment]
No tips, all free :) I'll probably add a more obvious way to see the bladeswarm class
