### ISSUE TITLE
Spoilers Shown by Default

### ISSUE THREAD

**Issue by mvanbaalen** [cmlenius/gloomhaven-card-browser#34]
Browsing to the app for the first time checkmarks all spoiled content, which I believe to be incorrect. It didn't used to be this way, and it definitely shouldn't be this way.

**Comment by cmlenius** [comment]
I will fix it soon, having issues with Google indexing my pages which i need to resolve first since having the spoilers off by default will cause google to think the pages are error pages and take them off google search 🤦
