### ISSUE TITLE
Bladeswarm

### ISSUE THREAD

**Issue by christopherboote** [cmlenius/gloomhaven-card-browser#39]
Hi
Now that Bladeswarm has been acknowledged by Cephalofair, do you intend to add it to your BRILLIANT tool?
Thanks
Chris

**Comment by cmlenius** [comment]
Glad you enjoy the tool. Bladeswarm is actually already there, its just hidden. You can see the character by going using the link below. I'll unhide the class now that its more well known.

https://www.gloomhavencards.com/gh/characters/BS

**Comment by christopherboote** [comment]
You're a star!

Thanks

Chris

On 11/01/2024 18:01, Cameron Lenius wrote:

> Glad you enjoy the tool. Bladeswarm is actually already there, its just 
> hidden. You can see the character by going using the link below. I 
> might unhide the class now that its more well known.
> 
> https://www.gloomhavencards.com/gh/characters/BS
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/cmlenius/gloomhaven-card-browser/issues/39#issuecomment-1887690303
[2]

**Comment by christopherboote** [comment]
Hmmmm

I now see the icon at the top, just before Diviner, but get

No Results
Check your spoiler settings or try changing your search & filters

CHris

On 11/01/2024 18:01, Cameron Lenius wrote:

> Glad you enjoy the tool. Bladeswarm is actually already there, its just 
> hidden. You can see the character by going using the link below. I 
> might unhide the class now that its more well known.
> 
> https://www.gloomhavencards.com/gh/characters/BS
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/cmlenius/gloomhaven-card-browser/issues/39#issuecomment-1887690303
[2]

**Comment by cmlenius** [comment]
Click on the `Settings` button in the top right and check the box next to `Bladeswarm` :)

**Comment by Kalaina** [comment]
There should probably be a spoiler-safe name for this in the settings menu, given that this is still a locked class, even if its existence isn't a super-spoiler anymore. I don't think there's an standard name for the icon yet, but some people have used "Crossed Swords" and that seems most likely for what the community will settle on.

**Comment by christopherboote** [comment]
The names used in Reddit have been Swords or Blades

I prefer the former, as 'Blades' is too close to the class name

On 14/01/2024 12:32, Kate Jo wrote:

> There should probably be a spoiler-safe name for this in the settings 
> menu, given that this is still a locked class, even if its existence 
> isn't a super-spoiler anymore. I don't think there's an standard name 
> for the icon yet, but some people have used "Crossed Swords" and that 
> seems most likely for what the community will settle on.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/cmlenius/gloomhaven-card-browser/issues/39#issuecomment-1890939805
[2]

**Comment by christopherboote** [comment]
Sorted, thanks

On 12/01/2024 21:18, Cameron Lenius wrote:

> Click on the Settings button in the top right and check the box next to 
> Bladeswarm :)
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/cmlenius/gloomhaven-card-browser/issues/39#issuecomment-1889962093
[2]

**Comment by christopherboote** [comment]
Hiya

Just noticed it's been misspelled Baldeswarm throughout 
https://www.gloomhavencards.com/gh/characters/BS :)

Chris

On 12/01/2024 21:18, Cameron Lenius wrote:

> Click on the Settings button in the top right and check the box next to 
> Bladeswarm :)
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/cmlenius/gloomhaven-card-browser/issues/39#issuecomment-1889962093
[2]
