### ISSUE TITLE
Other Languages?

### ISSUE THREAD

**Issue by Loremwriter** [cmlenius/gloomhaven-card-browser#42]
Hello,
I love your work and im wondering, if it's possible to translate the cards to different languages?
Id offer German as additional language and would help to translate all cards. 
Best regards

**Comment by cmlenius** [comment]
Thanks for volunteering however i don't think it will be possible. I would need quality images of all the cards in different languages which would be too difficult to collect. I could technically translate all the website text such as the dropdown menus but that would be kind of pointless if the card images themselves are in English.
