### ISSUE TITLE
Envelope V Details tab

### ISSUE THREAD

**Issue by Snowf1ake222** [cmlenius/gloomhaven-card-browser#50]
Details tab gives no results message like a locked class, but Card tab shows content. Can't find a way to unlock the content.

**Comment by cmlenius** [comment]
Are you talking about https://www.gloomhavencards.com/toa/characters/VQ?

**Comment by Snowf1ake222** [comment]
Yes. Although it works in one browser (an ad-block one) but not in Chrome on mobile.

**Comment by cmlenius** [comment]
Never played Trail of Ashes before, do you think i should just un-hide the class or is it better hidden?

**Comment by Snowf1ake222** [comment]
Definitely keep the class hidden. The CCUG wanted it to remain off the subreddit's custom content page when I was updating that.

Plus, if you know about it, it's very intuitive to find.
